language: java
jdk:
  - openjdk8
env:
  global:
  - CC_TEST_REPORTER_ID=3b8e5d9f5be5a2e67f63b704a6c2f96ffe460dc19af746fa137e2d70a110ec5d
  - secure: D0EJaT21U1mKdcc3vVtJ9Q2QBge6UXJK9GGfxt5hZVSaKq2Lv6iAcHfdmA8uGeJwCPl5pl4EhleRD2xYLFSmVgoFP58w9m9HM8JcDoqXPT21R5/ZAEduJ3rnKZA/V8py8j6pMra9DQEUyo1msYWaqkVPJT4YmPzdeO/NCnXhtYckHvyHae9lZyECO7yb/PjR0nKvp1o4xDqXDlF280deQGCW5kyY08g8/62YSjoFxhQUqA764grs6fbZOk46PygGsSBUwexkgrN+VNrBJJzwjq8ZEYzRl5G/q5cpVBSpUi6iUv9HK2MMDlXqgOx6ll4PuQlk5z7KCpABHF3DFfboB96FGDojwt2KFREc5iE8CqdH0b/hflz4tmf1rVLtdHCiPoAGfbJ2FOEV2Spsmyy2V37mwYItLkskZuYaijVXGVOF3ewdpDJDuiLC/bB8ceEoT5VfstwRMYoAWsgACKZ1DWQvqwlqmGr180Rw4xGlSpiEQZ10jeveehBw2XkBchMfl1VSKsG6AhLFCUBPfoQG2lqrqcECaw0J6KR7CkBTBs30xP9dlyKQgk5rh8X1gurMsVdoV3bPJYQ40vuPj99mxyD6u7+YA4r3HpTyLXASRZ0jdAxKXon974awwgncqCnPFNfFK/f5QuXplbJO10+he1ZEeivU/XvujuerHJG4IpE=
  - secure: nveeBxMPt63u2jdX1pgyMYxpHrFJaqSb3/Dgn+zPMCRHiy+qV/K5gNbVo+x/5d5VsWQwrN/6h3mIaABAJ5J4iII5KcXTBYJwKBMWtCMdcdrG3nTrr5pGeym8Mymz94AA7i917DstLaBr8a5O5KbEkZa2axX2yX5UvscZdM9tHRP4vB9mHDWftba18BbePkPR2zMxdOMXQ79eBFRfGSAL0Tr2n5q8Py3Lq75owZ9ot3DN1/PhqCWfC90buQVpHDb3x9tuZ+YjszVdfMhDUNuhnbZjk24hOtdzjOFnKdvjz3ukTsVNEUdqKL5X94FIDK+FG+U8clXI49m98pPaxjoWHVvJhTFQEUq5SbrRWqzC1lBMcZSOGmbpXlihOmiQZiuceKp9HBISXUQ14saCr579qwtdkWV1emaXrCehmDu1WCt1W/q5JsyJupGpdAQCtWTX6jRTrm+nyiY7Yy8TP+eqY8UbNT+c63WZIhrm8A1VcVY6MZQXG7V0VDxCj2OSA/HLSQD8Z+Uk0gm8tAqS+PELqSjCQNj0POjTohQsd1Z5QD7cQ4/wyClVANpDH65ZG70RIw5/KqYT9J1pEItUa52h66i9yLPkzwtc3Sa/OvxZ6O90OYm/EwE8dUvrfSfali4nHXa4+ITtq4nwPRF/NgDmPd/39fbA9Q9sQlpuDiIWwT4=
  - secure: jCr9UU6ukVYMWJGRnQXgXWeWZvM8ACsyAH2gpxuFgLtgcYWmwzb66jtEZE6ZKDB/yXyRerPyU9THpWndp1HRY1YiKkp8ZC9WhQ6pjkVwEiKHMOtFB+91IpM9gPUrmC5HIaOx77TnqEjzpZouMjH4KxgZBmYQnVe7Pv5jn3v+p1rvTNWDzKp8042bkn/8a7afuoNdCfJ+ED5vLr8kXjq4BXU0EQ52hTDnCRisHOA5+GRwMrlMJ4LuCD/GXJE/gRVlIsbNK44HCVPuoFjjQmh5UgWDhtCQMBIeVDdj5u3+kAvJABRebmkbvPj3qGj1vBgf/V7Yxa+GbEcInyJybGM8NPXX20Mcyp6ywJQegEZ5ATlNnxkpAlKrh4srbt3YaAxol8YG8ZuFCSDkTgnRz/c42v4x1yC+ywtSUgs1ofAH2GNmuc3TJrp9/6/aEXayFz2YMK++IZwW9CgfPoPgs1H7nr9EzXGknZ1a8h/VIfi7jcjqlTf2jGP0E85XtOBSeIQRgEE81tT5mkaHSUjMzSool2d5/VlnBW0J6QhgvUoDvk3lM8wt+o25g1Gy0Cnpi1c0GHhpoO+DIJ37Zvjqn6ag3UxyG77PNIQ8t53wKuX0fLxzHwe/fXaBMc7V6vPg0XpQP9u4LjUhz/jklVwkNICafYSeQDB8AJcj92dogt9HpEY=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/palette
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: OogcUzcMMIi+rDKjb27RTae0ywArbdc9nUTiKMYaYArHm94kvqj12eBtEK6tPBxMhk//J1X+euTORD/OuxWx/AaY1/fGPspk2w10gOCk+MYgjlaS4XzefeDUHo4a4sVHMRj1+CZc4unE7cxtBMF9rsnHdO8Pu7BEubnM/DPc+1EzQXzknv/bzF60VoPVuhRpzXgIKwOh1l2A64NietKduykS4Gi478hppK0Okpl6hgwDcE15z00/D54/JZgzVt+sjWP2UtLIlGrAJ6oTIGiXUnVSzUZ9YG9LiLDf/liT2ngtYcAYapfHeaBMDDrJBRl8tDi7len6tu9ISEurZaOgXMHm++Hqx7z13RGjTMytsyjV1BFTG2Nt2+p7qbarfw1b/l75gKza+rTg270nC/zEU3CsRDLrIEIrQj/Ibf6xLh6UhPjTZoeDX17NIwsy4XugEObvQHCaLbgTtNICElCAGKAmtQ3YMDQ9fK8oKFrdV2Z93UUJP12Y4aS/fBUD1JIT86rQOXdXlUH/l3McxOizVaduSfJJyj16Bw7EtYlnphGEYnroVBGB1Jqv5srT3niyHCaT09R8PDthrH6XGhw4zaSbBr35A2rc2BNUX2A/NVdm5/Eq6MKsxwsIv+o5QFJzpDwLEX5QhkVgnBCwvbCiF4dXh/Zuyt0bkWSb0uLX/eA=
  file: ".travis.yml"
  on:
    repo: trickl/palette
